sudo: required
language: python
services:
  - docker
env:
  global:
    # DOCKER_USER
    - secure: Sc7fFUmulANCHqHyJ+PzK4MojJ5QHDzzp0rE09fzeOawcjy/DNQRoTRCY5gVvFckzXwp7+s0nnMY5oxVgGOfSojr/QOcKDhvRTz/HaTzPYci3DbvwXoY6uRwTyjl3G9yP7xrDBEB2CS5fRlhS9kVLDLGCR/o19N2fr2wfeavP/ZyOEHo1bdc7MmWx1su6vm6WSK+5NNPsuRE8081ZxYF5cvRBwKDQ53W4+Ec5/A8YkEjy9m2zLuEMG8feBFlS7zsBwGhImStDKq5xG/cbVVtgh69PsSZXC3jNfBw7tOsc/m31HcZ9DwmcTmN+kDDWQoiH35UEVTGum24pgIlI+4aAassDfZ/NPszmsa9YE0TLgE23KMsS6z1w2cAKn0tHUlAA8+METucyTAyEJOx2Wk2Roxk4siWIJ1CJBQYmr8jPgZVmJX0zKWB5EcADp9QAWsapkZPv+faT/lpBZQOPUjdOI2AMRFfV+Dr+j1G/91KbfEXZdmw0HrtDOp2b4C+yH+QOKB21VZbm9DCBBpnseM4/eOdiJeR55FSmQt9piuMZJMD2z+KBePEw0cTmC99s+9HVD2OU2Yy+tGyQ/DQzrgSMcRrGusSBlpw7OXpZCMa/GD/fyUkgzfFhYIqc4hrW4OfRLPH7m9ohGOxY7DdoNdkG3sJVqrlCccviRO/9Eq3ciI=
    # DOCKER_PASSWORD
    - secure: DU8w/C1sgO53JzG+1oxeinVxyxTpL29iLs1JNW+dBplpoK9ocg6SPefpgSNyYG1+wYYweVWyaBqOsOyHQhX1yKH+AUhAnWa0E3gGigSqdYa06FksWBiFbAlDN+GQHnQm8W2o1n3LOFCJ2ncpjcDOXOXzu/NV+/HvL89GLETDv9655Oo/A8p7k5bdTrobwuLRzOqciPs3PZv2wLPcrJRHEocGghhoXHuNkQ4ddmGkoMwtkCvI3dYXlGMU2Yzf+I79A2d166e9TUWkvaEf+Xcwm4iwnMeuegmVflueY+Re7qfjOhfogv7bK6g0eXlOhWB9dpLMKrjLj/rhdP1pQ8YZ07YUFz/oPdOxSSC6t6eXvJsu72c8ijBpVySFgfsA+tIYre42T4wKiLn+hK0IUC0qlIP5VFngKw+Sa39w69XBZ/J0+Yva5rVCsBi502O3PaJi9qkY6kv3VL2YMmg3MuL2CX90dDDBJvtHf5KBHiShXEoJj+MjdG1MAnRFmBaMvC818F4UVvHrIg7HWrGsgqPHVsOpIUhc/ZptxMO44qTLAZCmX7PR+a3yGI5zVGya3ihdFb4JkBAkSyaiaUyrBmPkBGfAZIB+w1O2LpPmIx10f6eASOv6khuQQ69D0sJnHHMv63hsEo/YvrKCwfoCCbnlr8bRKliMJwczQwYjwcZVD8E=
    # IMAGE_REPO
    - secure: ELhN67w744U/8uNIIrXmvRCsaA57Upx6/n874U45IaY3ki/XGApwXfwB4y+x2in5Z9ytuMd0ItNdCZWATycJPKOygHdi1d6ktqOBAiTGPX9jbM3ZlQDF3GwjAyOLQyequQroflwfxJzav6/NrbLVb6q6EBVh5tmSAGGWvzEfF8GRQYVYQLubmq76ftooOGYh6LWWb2Ut8L7Q3m7e6ebUrnkvcrqNOc2Nel7D+C99HHNX/o/3GV7/3cxq/wMey/8M0fpDqEBvI+K1F0YjMBFPq2P2svdAcqoqowVBPzA7duOgI60gmAb8KclayeD7QDxrWa4YhSetyUs/BmmB9/hDSuRoKLcf0bXCtSg7vhoi6PeapC72Ml+vknQFoZrRLsl5xScFCuweMaaEMXUb0w6Rx72C0UBGJttvnwfY4QQ2xEihFBFKVEc3eC3CJH6pYqll4Jbr8qt2ijcDdFmYBWkQK1Cnz2EjQDUARgckwk19MfqxfFNObctHmolB3QK1Jna+U+iYaM/yMdtii3R5UXW/OyzDZc/JPqiPSTuNagvVIqqXE3PTrMqUV0hu7zQMLS8shXqIIA7cy6IXeDLLaE0gs5z1c/AJhfa+EUqmhmquCph0R9+YhazWGC9rhI5BE1GryoRidA2y/oyR4nLUoc8Vt3yqLqgS7bgRoEzrHpuI3NM=
  
script:
  - docker-compose build
  - sudo TEST_VIA=False docker-compose -f docker-compose.yml -f docker-compose.test.yml up --exit-code-from test

after_success:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
  - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo "test"; fi`
  - docker tag $IMAGE_REPO $IMAGE_REPO:$TAG
  - docker push $IMAGE_REPO:$TAG
