version: "3.7"
services:
  web:
    restart: always
    build: ./docsbox
    image: oikeusministerio/common-conversion:test
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./docsbox/certificate.pem:/home/docsbox/certificate.pem
      - ./media:/home/docsbox/media
    networks:
      - conversion-network
    extra_hosts:
      - it1.integraatiopalvelu.fi:${VIA_IP:-0.0.0.0}
      - logdev.om.fi:${GRAYLOG_IP:-0.0.0.0}
    environment:
      GRAYLOG_HOST: ${GRAYLOG_HOST:-nowhere}
      GRAYLOG_PORT: 445
      GRAYLOG_SOURCE: local
    command: gunicorn --config=docsbox/config/gunicorn.conf docsbox:app

  rqworker:
    restart: always
    image: oikeusministerio/common-conversion:test
    init: true
    depends_on:
      - redis
      - web
    volumes:
      - ./docsbox/certificate.pem:/home/docsbox/certificate.pem
      - ./media:/home/docsbox/media
      - /config:/root/.config/libreoffice/4/user
    networks:
      - conversion-network
    extra_hosts:
      - it1.integraatiopalvelu.fi:${VIA_IP:-0.0.0.0}
      - logdev.om.fi:${GRAYLOG_IP:-0.0.0.0}
    environment:
      GRAYLOG_HOST: ${GRAYLOG_HOST:-nowhere}
      GRAYLOG_PORT: 445
      GRAYLOG_SOURCE: local
    command: rq worker -c docsbox
 
  nginx:
    restart: always
    image: nginx
    depends_on:
      - web
    networks:
      - conversion-network
    ports:
      - "80:80"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
 
  redis:
    restart: always
    image: redis:latest
    networks:
      - conversion-network
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:

networks:
  conversion-network:
