version: "3"
services:
  web:
    restart: always
    build: ./docsbox
    image: oikeusministerio/common-conversion
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./docsbox:/home/docsbox
      - /media:/home/docsbox/media
    extra_hosts:
      - it1.integraatiopalvelu.fi:46.30.128.27
    command: gunicorn --config=docsbox/config/gunicorn.conf docsbox:app

  rqworker:
    restart: always
    build: ./docsbox
    image: oikeusministerio/common-conversion
    depends_on:
      - redis
      - web
    volumes:
      - ./docsbox:/home/docsbox
      - /media:/home/docsbox/media
    extra_hosts:
      - it1.integraatiopalvelu.fi:46.30.128.27
    command: rq worker -c docsbox
 
  rqscheduler:
    restart: always
    build: ./docsbox
    image: oikeusministerio/common-conversion
    depends_on:
      - redis
      - web
    command: rqscheduler -H redis -p 6379 -d 0
 
  nginx:
    restart: always
    image: nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
 
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata: