version: "3"
services:
 test:
   build: ./docsbox
   image: oikeusministerio/common-conversion
   depends_on:
     - redis
     - web
     - rqworker
   volumes:
     - ./docsbox:/home/docsbox
     - /media:/home/docsbox/media
   extra_hosts:
     - it1.integraatiopalvelu.fi:46.30.128.27
   command: nosetests
   environment:
    TEST_VIA: ${TEST_VIA}