version: "3"
services:
  web:
    restart: always
    build: ./docsbox
    image: oikeusministerio/common-conversion
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./docsbox:/home/docsbox
      - /media:/home/docsbox/media
    extra_hosts:
      - it1.integraatiopalvelu.fi:0.0.0.0
      - logdev.om.fi:0.0.0.0
    environment:
      GRAYLOG_HOST: 'logdev.om.fi'
      GRAYLOG_PORT: 444
      GRAYLOG_PATH: '/gelf'
      GRAYLOG_SOURCE: conversion.service.dev
    command: gunicorn --config=docsbox/config/gunicorn.conf docsbox:app

  rqworker:
    restart: always
    build: ./docsbox
    image: oikeusministerio/common-conversion
    depends_on:
      - redis
      - web
    volumes:
      - ./docsbox:/home/docsbox
      - /media:/home/docsbox/media
      - /config:/root/.config/libreoffice/4/user
    extra_hosts:
      - it1.integraatiopalvelu.fi:0.0.0.0
      - logdev.om.fi:0.0.0.0
    environment:
      GRAYLOG_HOST: 'logdev.om.fi'
      GRAYLOG_PORT: 444
      GRAYLOG_PATH: '/gelf'
      GRAYLOG_SOURCE: conversion.service.dev
    command: rq worker -c docsbox
 
  nginx:
    restart: always
    image: nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
 
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata: