web:
  restart: always
  build: ./docsbox
  expose:
    - "8000"
  links:
    - redis:redis
  volumes:
    - ./docsbox:/home/docsbox
    - /tmp/media:/home/docsbox/media
  extra_hosts:
    - it1.integraatiopalvelu.fi:46.30.128.27
  command: gunicorn --config=docsbox/config/gunicorn.conf docsbox:app

rqworker:
  restart: always
  build: ./docsbox
  links:
    - redis:redis
  volumes_from:
    - web
  command: rq worker -c docsbox

rqscheduler:
  restart: always
  build: ./docsbox
  links:
    - redis:redis
  volumes_from:
    - web
  command: rqscheduler -H redis -p 6379 -d 0

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web:web

redis:
  restart: always
  image: redis:latest
  expose:
    - "6379"
  volumes:
    - redisdata:/data
