version: "3"
services:
 test:
   build: ./docsbox
   image: oikeusministerio/common-conversion
   depends_on:
     - redis
     - web
     - rqworker
     - rqscheduler
   volumes:
     - ./docsbox:/home/docsbox
     - /tmp/media:/home/docsbox/media
   extra_hosts:
     - it1.integraatiopalvelu.fi:46.30.128.27
   command: nosetests